---
name: test
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  foo:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.42.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          permissions: >-
            {
              "contents": "read"
            }
          repositories: >-
            [
              "test-private-terraform-module"
            ]
      - run: |
          git config --global url."https://oauth2:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}".insteadOf "https://github.com/${GITHUB_REPOSITORY_OWNER}"
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
      - run: terraform init
      - run: |
          git config --global --unset url."https://oauth2:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}".insteadOf
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
      - run: terraform plan
